[tool.briefcase]
project_name = "exemplo"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/exemplo"
license.file = "LICENSE"
author = "Jane Developer"
author_email = "jane@example.com"

[tool.briefcase.app.exemplo]
formal_name = "exemplo"
description = "My first application"
long_description = """More details about the app should go here.
"""
sources = [
    "src/exemplo",
]
test_sources = [
    "tests",
]

console_app = true
requires = ['cyclopts']
test_requires = [
    "pytest",
]

[tool.briefcase.app.exemplo.macOS]
universal_build = true
requires = []

[tool.briefcase.app.exemplo.linux]
requires = []

[tool.briefcase.app.exemplo.linux.system.debian]
system_requires = []

system_runtime_requires = []

[tool.briefcase.app.exemplo.linux.system.rhel]
system_requires = []

system_runtime_requires = []

[tool.briefcase.app.exemplo.linux.system.suse]
system_requires = []

system_runtime_requires = []

[tool.briefcase.app.exemplo.linux.system.arch]
system_requires = []

system_runtime_requires = []

[tool.briefcase.app.exemplo.linux.flatpak]
flatpak_runtime = "org.freedesktop.Platform"
flatpak_runtime_version = "24.08"
flatpak_sdk = "org.freedesktop.Sdk"

[tool.briefcase.app.exemplo.windows]
requires = []


[tool.briefcase.app.exemplo.iOS]
supported = false

[tool.briefcase.app.exemplo.android]
supported = false

[tool.briefcase.app.exemplo.web]
supported = false

