[tool.briefcase]
project_name = "exemplo"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/exemplo"
license.file = "LICENSE"
author = "Jane Developer"
author_email = "jane@example.com"

[tool.briefcase.app.exemplo]
formal_name = "exemplo"
description = "Meu primeiro exemplo"
long_description = """More details about the app should go here."""
sources = ["exemplo"]
test_sources = ["tests"]
console_app = true
requires = ['cyclopts']
test_requires = ["pytest"]