name: CI
on:
  push

concurrency:
  group: ${{ github.workflow}}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  FORCE_COLOR: "1"

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: Test and Package
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        target: [ "Flatpak", "AppImage", "Archlinux" ]
        include:
          - target: "AppImage"
            platform: "linux"
            output-format: "appimage"
            runs-on: "ubuntu-latest"

          - target: "Flatpak"
            platform: "linux"
            output-format: "flatpak"
            runs-on: "ubuntu-latest"

          - target: "Archlinux"
            platform: "linux"
            output-format: "system"
            runs-on: "ubuntu-latest"
            briefcase-args: "--target archlinux"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install flatpak
        if: matrix.target == 'Flatpak'
        run: sudo apt install flatpak flatpak-builder

      - name: Install Briefcase
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install briefcase

      - name: Build App
        run: |
          briefcase build \
            ${{ matrix.platform || matrix.target }} \
            ${{ matrix.output-format }} \
            --test --no-input --log \
            ${{ matrix.briefcase-args }}

      - name: Package App
        run: |
          briefcase package \
            ${{ matrix.platform || matrix.target }} \
            ${{ matrix.output-format }} \
            --update --adhoc-sign --no-input --log \
            ${{ matrix.briefcase-args }}

      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: exemplo-${{ matrix.target }}
          path: dist
          if-no-files-found: error

      - name: Upload Log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Log-Failure-${{ matrix.target }}
          path: logs/*